files(
  name = "makefile",
  paths = ["Makefile"]
)

rule(
  name = "nothing",
  sources = ["makefile"],
  commands = ["make nothing"],
  outputs = []
)

rule(
  name = "something",
  sources = ["makefile"],
  commands = ["make something"],
  outputs = []
)
